@echo off
taskkill /f /im chrome.exe
taskkill /f /im chrome_proxy.exe
taskkill /f /im chromium.exe
taskkill /f /im chromium_helper.exe
taskkill /f /im msedge.exe
taskkill /f /im msedgewebview2.exe
taskkill /f /im msedge_proxy.exe
taskkill /f /im msedgeupdate.exe
taskkill /f /im msedgeupdatebroker.exe
taskkill /f /im brave.exe
taskkill /f /im brave_proxy.exe
taskkill /f /im brave_vpn.exe
taskkill /f /im brave_crashpad_handler.exe
taskkill /f /im opera.exe
taskkill /f /im opera_gx.exe
taskkill /f /im opera_autoupdate.exe
taskkill /f /im opera_crashreporter.exe
taskkill /f /im vivaldi.exe
taskkill /f /im vivaldi_proxy.exe
taskkill /f /im vivaldi_crashpad_handler.exe
taskkill /f /im firefox.exe
taskkill /f /im firefoxprivate.exe
taskkill /f /im firefoxcrashreporter.exe
taskkill /f /im firefoxinstaller.exe
taskkill /f /im firefoxupdater.exe
taskkill /f /im waterfox.exe
taskkill /f /im waterfoxcrashreporter.exe
taskkill /f /im palemoon.exe
taskkill /f /im palemoon-crashreporter.exe
taskkill /f /im librewolf.exe
taskkill /f /im basilisk.exe
taskkill /f /im tor.exe
taskkill /f /im torbrowser.exe
taskkill /f /im torbrowser-launcher.exe
taskkill /f /im iexplore.exe
taskkill /f /im MicrosoftEdge.exe
taskkill /f /im browser.exe
taskkill /f /im browser_broker.exe
taskkill /f /im browser_crash_handler.exe
taskkill /f /im browser_gpu.exe
taskkill /f /im browser_renderer.exe
taskkill /f /im epic.exe
taskkill /f /im iron.exe
taskkill /f /im maxthon.exe
taskkill /f /im mxbrowser.exe
taskkill /f /im mxupdate.exe
taskkill /f /im slimjet.exe
taskkill /f /im dragon.exe
taskkill /f /im yandex.exe
taskkill /f /im yandexbrowser.exe
taskkill /f /im avastbrowser.exe
taskkill /f /im avgbrowser.exe
taskkill /f /im 360chrome.exe
taskkill /f /im 360se.exe
taskkill /f /im qqbrowser.exe
taskkill /f /im ucbrowser.exe
taskkill /f /im sogouexplorer.exe
taskkill /f /im sputnik.exe
taskkill /f /im coccoc.exe
taskkill /f /im naverwhale.exe
taskkill /f /im whale.exe
taskkill /f /im centbrowser.exe
taskkill /f /im torch.exe
taskkill /f /im midori.exe
taskkill /f /im falkon.exe
taskkill /f /im qutebrowser.exe
taskkill /f /im otter-browser.exe
taskkill /f /im seamonkey.exe
taskkill /f /im k-meleon.exe
taskkill /f /im netsurf.exe
taskkill /f /im dooble.exe
taskkill /f /im surf.exe
taskkill /f /im luakit.exe
taskkill /f /im webview2.exe
taskkill /f /im webview_host.exe
taskkill /f /im webview_loader.exe
taskkill /f /im gpu-process.exe
taskkill /f /im renderer.exe
taskkill /f /im utility.exe
taskkill /f /im network-service.exe
taskkill /f /im crashpad_handler.exe
taskkill /f /im software_reporter_tool.exe
taskkill /f /im browser_assistant.exe
taskkill /f /im browser_assistant_service.exe
taskkill /f /im browser_update.exe
taskkill /f /im browser_update_service.exe
taskkill /f /im browser_crash_reporter.exe
taskkill /f /im browser_gpu_process.exe
taskkill /f /im browser_renderer_process.exe
taskkill /f /im browser_utility_process.exe
